places=['colombia', 'japan', 'bali', 'hawaii', 'peru', 'san andres', 'switzerland','maldives']
print(f'\nThis is the list in its original order\n{places}')
print('\nThis is the list organized in alphabetical order')
print(sorted(places))
print(f'\nThis is the original list still in its original order\n{places}')
print('\nThis is the list printed in reverse alphabetical order')
print(sorted(places, reverse=True))
print(f'\nThis is still the original list in its original order\n{places}')
places.reverse()
print(f'\nThis is the orignal list printed in reverse order\n{places}')
places.reverse()
print(f'\nThis is the list reversed back to its original order\n{places}')
places.sort()
print(f'\nThis is the original list organized in alphabetical order permanently\n{places}')
places.sort(reverse=True)
print(f"\nThis is the original list printed in reverse alphabetical order permanently\n{places}\n")